# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('user', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=140)),
                ('lastName', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=140)),
            ],
        ),
    ]
