# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logNote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='userId',
        ),
    ]
